"""PostgreSQL backend (team / server mode).

PatchQuest's persistence code is written against a small portable SQL subset. This module gives it a
connection with the same surface as ``sqlite3`` (``execute`` returning a cursor with ``fetchone``/``fetchall``/
``rowcount``/``lastrowid``, rows readable by name or position) and translates the few dialect differences:

* ``?`` placeholders -> ``%s`` (string literals are left alone);
* ``INSERT OR IGNORE`` -> ``ON CONFLICT DO NOTHING``;
* DDL: ``AUTOINCREMENT`` -> identity columns, ``REAL`` -> ``DOUBLE PRECISION``, ``datetime('now')``;
* ``PRAGMA table_info`` -> ``information_schema``; ``BEGIN IMMEDIATE`` -> a transaction-scoped advisory lock;
* SQLite ``BEFORE UPDATE/DELETE ... RAISE(ABORT)`` triggers -> PL/pgSQL trigger functions;
* ``lastrowid`` -> ``RETURNING`` of the table's identity column.

Connections come from a pool; every checkout is one transaction that commits when ``get_db`` exits cleanly and
rolls back on an exception, exactly like the SQLite path. ``psycopg`` is an optional dependency
(``pip install 'patchquest[server]'``).
"""

from __future__ import annotations

import re
import sqlite3
import threading
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from decimal import Decimal
from functools import lru_cache
from typing import Any

WRITE_LOCK_KEY = 727_270_001  # BEGIN IMMEDIATE: one holder at a time across processes
DIALECT = "postgresql"


# --------------------------------------------------------------------------- translation
def _split_literals(sql: str) -> list[tuple[bool, str]]:
    """Split into (is_string_literal, text) so rewriting never touches quoted text."""
    parts: list[tuple[bool, str]] = []
    buf: list[str] = []
    i, n = 0, len(sql)
    while i < n:
        ch = sql[i]
        if ch == "'":
            if buf:
                parts.append((False, "".join(buf)))
                buf = []
            j = i + 1
            while j < n:
                if sql[j] == "'" and sql[j + 1:j + 2] == "'":
                    j += 2
                    continue
                if sql[j] == "'":
                    break
                j += 1
            parts.append((True, sql[i:j + 1]))
            i = j + 1
        else:
            buf.append(ch)
            i += 1
    if buf:
        parts.append((False, "".join(buf)))
    return parts


_NOW = "to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')"
_TRIGGER = re.compile(
    r"CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?(?P<name>\w+)\s+BEFORE\s+(?P<event>UPDATE|DELETE)\s+ON\s+(?P<table>\w+)\s*"
    r"(?:WHEN\s+(?P<when>.*?))?\s*BEGIN\s+SELECT\s+RAISE\(ABORT,\s*'(?P<msg>[^']*)'\)\s*;\s*END", re.I | re.S)
_INSERT_TABLE = re.compile(r"^\s*INSERT\s+INTO\s+(\w+)", re.I)


@lru_cache(maxsize=2048)
def translate(sql: str) -> tuple[str, ...]:
    """The PostgreSQL statement(s) for one SQLite-flavoured statement."""
    stripped = sql.strip().rstrip(";")
    upper = stripped.upper()
    if upper.startswith("CREATE TRIGGER"):
        return _trigger(stripped)
    if upper.startswith("PRAGMA TABLE_INFO"):
        table = re.search(r"\((\w+)\)", stripped)
        name = table.group(1) if table else ""
        return (f"SELECT ordinal_position - 1 AS cid, column_name AS name FROM information_schema.columns "
                f"WHERE table_schema = current_schema() AND table_name = '{name}' ORDER BY ordinal_position",)
    out = []
    for is_literal, text in _split_literals(stripped):
        if is_literal:
            out.append(text.replace("%", "%%"))  # psycopg parses placeholders even inside literals
            continue
        text = text.replace("%", "%%").replace("?", "%s")
        text = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", text, flags=re.I)
        text = re.sub(r"\bAUTOINCREMENT\b", "", text, flags=re.I)
        text = re.sub(r"\bREAL\b", "DOUBLE PRECISION", text, flags=re.I)
        out.append(text)
    result = "".join(out)
    result = re.sub(r"datetime\(\s*'now'\s*\)", _NOW, result, flags=re.I)
    if re.match(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO", result, re.I):
        result = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", result, count=1, flags=re.I)
        if "ON CONFLICT" not in result.upper():
            result += " ON CONFLICT DO NOTHING"
    return (result,)


def _trigger(sql: str) -> tuple[str, ...]:
    m = _TRIGGER.match(sql)
    if m is None:
        raise ValueError(f"cannot translate trigger: {sql[:80]}")
    name, event, table, when, msg = m["name"], m["event"].upper(), m["table"], m["when"], m["msg"].replace("'", "''")
    cond = None
    if when:
        cond = re.sub(r"(\w+\.\w+)\s+IS\s+(?=(?:OLD|NEW)\.)", r"\1 IS NOT DISTINCT FROM ", when.strip())
    body = f"IF {cond} THEN RAISE EXCEPTION '{msg}' USING ERRCODE = 'integrity_constraint_violation'; END IF;" if cond else \
        f"RAISE EXCEPTION '{msg}' USING ERRCODE = 'integrity_constraint_violation';"
    returns = "OLD" if event == "DELETE" else "NEW"
    return (
        f"CREATE OR REPLACE FUNCTION trg_{name}() RETURNS trigger AS $$ BEGIN {body} RETURN {returns}; END $$ LANGUAGE plpgsql",
        f"DROP TRIGGER IF EXISTS {name} ON {table}",
        f"CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW EXECUTE FUNCTION trg_{name}()",
    )


# --------------------------------------------------------------------------- rows and cursors
class Row:
    """Readable by position or name, like ``sqlite3.Row``."""

    __slots__ = ("_names", "_values")

    def __init__(self, names: Sequence[str], values: Sequence[Any]) -> None:
        self._names, self._values = tuple(names), tuple(values)

    def __getitem__(self, key: int | str | slice) -> Any:
        if isinstance(key, str):
            try:
                return self._values[self._names.index(key)]
            except ValueError:
                raise IndexError(f"No item with that key: {key}") from None
        return self._values[key]

    def keys(self) -> list[str]:
        return list(self._names)

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Row) and self._values == other._values and self._names == other._names

    def __hash__(self) -> int:
        return hash(self._values)

    def __repr__(self) -> str:
        return f"Row({dict(zip(self._names, self._values, strict=True))!r})"


def _row_factory(cursor: Any) -> Any:
    names = [c.name for c in cursor.description] if cursor.description else []

    def make(values: Sequence[Any]) -> Row:
        return Row(names, values)

    return make


class Cursor:
    def __init__(self, cur: Any, lastrowid: int | None = None) -> None:
        self._cur, self.lastrowid = cur, lastrowid

    @property
    def rowcount(self) -> int:
        return int(self._cur.rowcount)

    @property
    def description(self) -> Any:
        return self._cur.description

    def fetchone(self) -> Row | None:
        return self._cur.fetchone() if self._cur.description else None

    def fetchall(self) -> list[Row]:
        return self._cur.fetchall() if self._cur.description else []

    def __iter__(self) -> Iterator[Row]:
        return iter(self.fetchall())


_identity_cache: dict[tuple[str, str], str | None] = {}
_identity_lock = threading.Lock()


class Connection:
    """The ``sqlite3.Connection`` surface PatchQuest uses, over one pooled psycopg connection."""

    dialect = DIALECT

    def __init__(self, raw: Any, schema: str) -> None:
        self._raw, self._schema = raw, schema

    # ------------------------------------------------------------ identity columns (for lastrowid)
    def _identity_column(self, table: str) -> str | None:
        key = (self._schema, table.lower())
        with _identity_lock:
            if key in _identity_cache:
                return _identity_cache[key]
        with self._raw.cursor() as cur:
            cur.execute("SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() "
                        "AND table_name = %s AND is_identity = 'YES'", (key[1],))
            found = cur.fetchone()
        column = found[0] if found else None
        if column is not None or self._table_exists(key[1]):
            with _identity_lock:
                _identity_cache[key] = column
        return column

    def _table_exists(self, table: str) -> bool:
        with self._raw.cursor() as cur:
            cur.execute("SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = %s", (table,))
            return cur.fetchone() is not None

    # ------------------------------------------------------------ execution
    def execute(self, sql: str, params: Sequence[Any] | dict[str, Any] = ()) -> Cursor:
        head = sql.lstrip()[:20].upper()
        if head.startswith("BEGIN"):
            if "IMMEDIATE" in head:  # SQLite's "take the write lock now": here, a transaction-scoped advisory lock
                self._raw.execute("SELECT pg_advisory_xact_lock(%s)", (WRITE_LOCK_KEY,))
            return Cursor(self._raw.cursor())
        if head.startswith(("COMMIT", "ROLLBACK")):
            (self._raw.commit if head.startswith("COMMIT") else self._raw.rollback)()
            return Cursor(self._raw.cursor())
        if head.startswith("PRAGMA") and "TABLE_INFO" not in head:
            return Cursor(self._raw.cursor())  # SQLite tuning knobs have no PostgreSQL equivalent
        statements = translate(sql)
        values = tuple(int(p) if isinstance(p, bool) else p for p in params) if not isinstance(params, dict) else params
        cur: Any = None
        lastrowid: int | None = None
        for stmt in statements:
            cur = self._raw.cursor(row_factory=_row_factory)
            returning = None
            m = _INSERT_TABLE.match(stmt)
            if m and "RETURNING" not in stmt.upper() and len(statements) == 1:
                returning = self._identity_column(m.group(1))
                if returning:
                    stmt = f"{stmt} RETURNING {returning}"
            try:
                cur.execute(stmt, values if len(statements) == 1 else ())
            except Exception as exc:
                raise _wrap(exc) from exc
            if returning and cur.description:
                row = cur.fetchone()
                lastrowid = int(row[0]) if row is not None else None
                cur = _EmptyAfterReturning(cur)
        return Cursor(cur, lastrowid)

    def executescript(self, script: str) -> None:
        from patchquest.persistence.migrations import statements

        for stmt in statements(script):
            self.execute(stmt)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:  # pooled: returning it is the pool context manager's job
        return None


class _EmptyAfterReturning:
    """A cursor whose RETURNING row was consumed for ``lastrowid``: it reports no result set."""

    description = None

    def __init__(self, cur: Any) -> None:
        self._cur = cur

    @property
    def rowcount(self) -> int:
        return int(self._cur.rowcount)

    def fetchone(self) -> None:
        return None

    def fetchall(self) -> list[Any]:
        return []


class IntegrityError(sqlite3.IntegrityError):
    """A constraint failed (unique, foreign key, not null, or an append-only trigger). A subclass of sqlite3's, so
    persistence code and tests that handle that type handle both backends."""


class OperationalError(sqlite3.OperationalError):
    """The database could not be reached or timed out (connection loss, lock timeout, deadlock)."""


def _wrap(exc: Exception) -> Exception:
    import psycopg

    if isinstance(exc, psycopg.errors.IntegrityError):
        return IntegrityError(str(exc))
    if isinstance(exc, (psycopg.errors.OperationalError, psycopg.errors.DeadlockDetected, psycopg.errors.LockNotAvailable,
                        psycopg.errors.SerializationFailure)):
        return OperationalError(str(exc))
    return exc


# --------------------------------------------------------------------------- pool
_pools: dict[tuple[str, str], Any] = {}
_pool_lock = threading.Lock()


def _configure(raw: Any) -> None:
    from psycopg.adapt import Loader

    class NumberLoader(Loader):
        """SUM/AVG return NUMERIC; give back an int when it is whole, like SQLite does."""

        def load(self, data: Any) -> Any:
            d = Decimal(bytes(data).decode())
            return int(d) if d == d.to_integral_value() else float(d)

    raw.adapters.register_loader("numeric", NumberLoader)
    raw.commit()


def pool_for(dsn: str, schema: str | None, size: int = 20) -> Any:
    from psycopg_pool import ConnectionPool

    key = (dsn, schema or "")
    with _pool_lock:
        pool = _pools.get(key)
        if pool is None:
            options = f"-c search_path={schema}" if schema else None
            pool = ConnectionPool(dsn, min_size=1, max_size=size, kwargs={"autocommit": False, **({"options": options} if options else {})},
                                  configure=_configure, open=True, name=f"patchquest-{schema or 'default'}", timeout=30)
            _pools[key] = pool
        return pool


def close_pool(dsn: str, schema: str | None) -> None:
    with _pool_lock:
        pool = _pools.pop((dsn, schema or ""), None)
    if pool is not None:
        pool.close()
    with _identity_lock:
        for k in [k for k in _identity_cache if k[0] == (schema or "")]:
            del _identity_cache[k]


@contextmanager
def connect(dsn: str, schema: str | None) -> Iterator[Connection]:
    pool = pool_for(dsn, schema)
    with pool.connection() as raw:
        yield Connection(raw, schema or "")
