"""A sanitized diagnostics bundle for a bug report: enough to see what is wrong, nothing that is yours.

Included: versions and platform, the doctor results, the configuration (environment-variable *names*, never values),
schema version and table counts, queue state, endpoint health, and summaries of recent failed runs (id, typed failure,
message). With ``run_id`` also that run's event history (types, phases, messages).
Never included: repository source, diffs, model prompts or answers, task text, API tokens or keys. Everything textual
passes the secret redactor, and your home directory is shown as ``~``.
"""

from __future__ import annotations

import json
import platform
import re
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from patchquest import __version__
from patchquest.database import get_db, get_db_path
from patchquest.tools.secret_guard import redact_secrets

README = """PatchQuest support bundle
=========================
Generated by `patchquest doctor --bundle`. Share it with the maintainers to help diagnose a problem.

Contains: versions, doctor results, configuration (environment variable names only), schema version, table counts,
queue state, endpoint health, summaries of recent failed runs{run}.
Does NOT contain: repository source code, diffs, model prompts or answers, task text, API tokens or keys.
Text is passed through a secret redactor and your home directory is shown as '~', but redaction is pattern-based:
read the files before sharing them if your task messages might contain sensitive details.
"""


def scrub(text: Any) -> Any:
    """Redact secrets and hide the home directory in any string (recursively through containers)."""
    if isinstance(text, str):
        out = redact_secrets(text).replace(str(Path.home()), "~")
        return re.sub(r"(https?://)[^/@\s]+@", r"\1***@", out)  # credentials in URLs
    if isinstance(text, dict):
        return {k: scrub(v) for k, v in text.items()}
    if isinstance(text, list):
        return [scrub(v) for v in text]
    return text


def _config() -> dict[str, Any]:
    from patchquest.config import get_config

    return scrub(get_config().model_dump())  # the config holds variable *names*; values are never in it


def _database() -> dict[str, Any]:
    from patchquest.persistence.migrations import current_version
    from patchquest.persistence.schema import MIGRATIONS

    path = get_db_path()
    if not path.exists():
        return {"exists": False}
    with get_db() as conn:
        counts = {}
        for table in ("runs", "run_events", "checkpoints", "approvals", "audit_log", "workflows", "workflow_runs"):
            if conn.execute("SELECT 1 FROM sqlite_master WHERE name = ?", (table,)).fetchone():
                counts[table] = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        by_status = {r[0]: r[1] for r in conn.execute("SELECT status, COUNT(*) FROM runs GROUP BY status")}
        return {"exists": True, "size_mb": round(path.stat().st_size / 1048576, 2), "schema_version": current_version(conn),
                "expected_schema_version": max(m.version for m in MIGRATIONS), "counts": counts, "runs_by_status": by_status}


def _failures(limit: int = 25) -> list[dict[str, Any]]:
    path = get_db_path()
    if not path.exists():
        return []
    out = []
    with get_db() as conn:
        rows = conn.execute("SELECT id, status, outcome, verdict, failure_kind, attempt, provider, model, created_at, completed_at "
                            "FROM runs WHERE status IN ('failed', 'interrupted', 'cancelled') ORDER BY created_at DESC LIMIT ?",
                            (limit,)).fetchall()
        for r in rows:
            event = conn.execute("SELECT message, payload_json FROM run_events WHERE run_id = ? AND type = 'run_failed' ORDER BY id DESC LIMIT 1",
                                 (r["id"],)).fetchone()
            failure = (json.loads(event["payload_json"]).get("failure") if event and event["payload_json"] else None) or {}
            out.append(scrub({**{k: r[k] for k in r.keys()}, "message": (event["message"] if event else None),
                              "failure_kind": failure.get("kind", r["failure_kind"]), "detail": failure.get("detail")}))
    return out


def _run_history(run_id: str) -> dict[str, Any]:
    from patchquest.persistence import ledger

    with get_db() as conn:
        events = ledger.read(conn, run_id, limit=5000)
    return {"run_id": run_id, "events": [scrub({"id": e["id"], "type": e["type"], "phase": e["phase"], "status": e["status"],
                                                "message": e["message"], "actor": e["actor"], "attempt": e["attempt"],
                                                "created_at": e["created_at"]}) for e in events]}


def build(dest: Path, *, run_id: str | None = None) -> list[str]:
    """Write the bundle to ``dest`` (a .zip; refuses to overwrite). Returns the names of the files inside."""
    from patchquest.doctor import run_checks
    from patchquest.providers import health

    if dest.exists():
        raise FileExistsError(f"{dest} already exists; choose a new name")
    parts: dict[str, Any] = {
        "manifest.json": {"patchquest": __version__, "python": platform.python_version(), "platform": platform.platform(),
                          "created_at": datetime.now(UTC).isoformat(), "includes_run": run_id},
        "doctor.json": scrub([c.to_dict() for c in run_checks()]),
        "config.json": _config(),
        "database.json": _database(),
        "failures.json": _failures(),
        "endpoint_health.json": scrub(health.snapshot()),
    }
    if run_id:
        parts[f"run-{run_id[:12]}.json"] = _run_history(run_id)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as bundle:
        bundle.writestr("README.txt", README.format(run=" and one run's event history" if run_id else ""))
        for name, data in parts.items():
            bundle.writestr(name, json.dumps(data, indent=2, default=str) + "\n")
    dest.chmod(0o600)
    return ["README.txt", *parts]
